    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
            <div class="container">
                
                <a href="/" class="navbar-brand">
                    <img src="/img/Emporio_rinaldi.png" id="imagem">
                </a>

                <div class="login-button">
                    <a href="/entrar" class="btn">Entrar</a>
                </div>

            </div>
        </nav>
    </header>

    <section>

        <div class="d-flex cont2 bg-dark">
            <div class="row">
                <div class="col-md-12">
                    <div class="d-flex">

                    <nav class="navbar list-group margem">
                        <li class="navbar-nav ml-auto text1">
                            <a href="" class="list-group-item list1"><img src="/img/distintivo-de-desconto.png" class="icone2"><br/>Promoções</a>
                            <a href="" class="list-group-item list1"><img src="/img/vinho.png" class="icone2"><br/>Vinhos</a>
                            <a href="" class="list-group-item list1"><img src="/img/bebida-energetica.png" class="icone2"><br/>Energéticos</a>
                            <a href="" class="list-group-item list1"><img src="/img/refrigerantes.png" class="icone2"><br/>Refris</a>
                        </li>
                    </nav>

                    <img src="/img/Emporio_rinaldi.png" height="349px" class="bg-dark">
    
                    <nav class="navbar list-group margem">
                        <li class="navbar-nav mr-auto text1">
                            <a href="" class="list-group-item list1"><img src="/img/cerveja.png" class="icone2"><br/>Cervejas</a>
                            <a href="" class="list-group-item list1"><img src="/img/licor.png" class="icone2"><br/>Destilados</a>
                            <a href="" class="list-group-item list1"><img src="/img/bebida-alcoolica.png" class="icone2"><br/>Espumantes</a>
                            <a href="" class="list-group-item list1"><img src="/img/garrafa-de-agua.png" class="icone2"><br/>Águas</a>
                        </li>
                    </nav>

                    </div>
                </div>
            </div>
        </div>

        <!-- Barra de pesquisa -->
        <nav class="navbar-expand-md navbar-dark bg-dark naveg">

            <!-- Hamburguer -->
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navegacao2">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Navegação -->
            <div class="collapse navbar-collapse justify-content-center" id="navegacao2">
        
            <ul class="navbar-nav">

                <li class="nav-item dropdown">
                    <a href="" class="nav-link pesquisa dropdown-toggle" data-toggle="dropdown">Destaques</a>
                    <div class="dropdown-menu">
                        <a href="" class="dropdown-item">➥ Mais pedidos</a>
                        <a href="" class="dropdown-item">➥ Importados</a>
                        <a href="" class="dropdown-item">➥ Para presentear</a>
                    </div>
                </li>

                <li class="nav-item dropdown">
                    <a href="" class="nav-link pesquisa dropdown-toggle" data-toggle="dropdown">Kits</a>
                    <div class="dropdown-menu">
                        <a href="" class="dropdown-item">➥ Edição especial</a>
                        <a href="" class="dropdown-item">➥ Edição mensal</a>
                        <a href="" class="dropdown-item">➥ Outros</a>
                    </div>
                </li>

            <!-- Formulário -->
            <form class="form-inline mb-2">
                <input type="text" class="form-control" placeholder="pesquisar...">
                <button class="btn btn-outline-light"><img src="/img/lupa1.png" class="icone3"></button>
            </form>

            </ul>

            </div>
        </nav>


        <!-- Area de vendas -->
        <div class="main-container">
            <div class="tab-nav-bar">
                <div class="tab-navigation">
                <i class="uil uil-angle-left left-btn"></i>
                <i class="uil uil-angle-right right-btn"></i>
                <ul class="tab-menu">

                    <li class="card tab-btn">
                        <div class="img_produtos">
                            <img src="/img/whisky-jack-daniels.jpg" class="bebidas">
                            <span class="desconto">27%<br />OFF</span>
                        </div>
                        <div>
                            <h4>Whisky Jack Daniel's<br />1000ml</h4>
                            <h5><span>179,90</span> | 123,41</h5>
                            <a href="pagina2.html" class="btn btn-dark">+Carrinho</a>
                        </div>
                    </li>
                
                    <li class="card tab-btn">
                        <div class="img_produtos">
                            <img src="/img/6405-whisky-white-horse-1l.jpg" class="bebidas">
                            <span class="desconto">25%<br />OFF</span>
                        </div>
                         <div>
                            <h4>Whisky White Horse<br />1000ml</h4>
                            <h5><span>109,48</span> | 78,00</h5>
                            <a href="pagina2.html" class="btn btn-dark">+Carrinho</a>
                        </div>
                    </li>

                    <li class="card tab-btn">
                        <div class="img_produtos">
                            <img src="/img/88970-licor-de-whisky-passport-sabor-mel-670ml.jpg" class="bebidas">
                            <span class="desconto">25%<br />OFF</span>
                        </div>
                        <div>
                            <h4>Whisky Passport Honey<br />670ml</h4>
                            <h5><span>67,00</span> | 47,74</h5>
                            <a href="pagina2.html" class="btn btn-dark">+Carrinho</a>
                        </div>
                    </li>

                    <li class="card tab-btn">
                        <div class="img_produtos">
                            <img src="/img/Whisky-Jack-Honney.png" class="bebidas">
                            <span class="desconto">27%<br />OFF</span>
                        </div>
                        <div>
                            <h4>Whisky Jack Daniel's Honey<br />1000ml</h4>
                            <h5><span>179,90</span> | 123,41</h5>
                            <a href="pagina2.html" class="btn btn-dark">+Carrinho</a>
                        </div>
                    </li>

                    <li class="card tab-btn">
                        <div class="img_produtos">
                            <img src="/img/whisky-jack-daniels.jpg" class="bebidas">
                            <span class="desconto">27%<br />OFF</span>
                        </div>
                        <div>
                            <h4>Whisky Jack Daniel's<br />1000ml</h4>
                            <h5><span>179,90</span> | 123,41</h5>
                            <a href="pagina2.html" class="btn btn-dark">+Carrinho</a>
                        </div>
                    </li>
                
                    <li class="card tab-btn">
                        <div class="img_produtos">
                            <img src="/img/6405-whisky-white-horse-1l.jpg" class="bebidas">
                            <span class="desconto">25%<br />OFF</span>
                        </div>
                         <div>
                            <h4>Whisky White Horse<br />1000ml</h4>
                            <h5><span>109,48</span> | 78,00</h5>
                            <a href="pagina2.html" class="btn btn-dark">+Carrinho</a>
                        </div>
                    </li>

                    <li class="card tab-btn">
                        <div class="img_produtos">
                            <img src="/img/88970-licor-de-whisky-passport-sabor-mel-670ml.jpg" class="bebidas">
                            <span class="desconto">25%<br />OFF</span>
                        </div>
                        <div>
                            <h4>Whisky Passport Honey<br />670ml</h4>
                            <h5><span>67,00</span> | 47,74</h5>
                            <a href="pagina2.html" class="btn btn-dark">+Carrinho</a>
                        </div>
                    </li>

                    <li class="card tab-btn">
                        <div class="img_produtos">
                            <img src="/img/Whisky-Jack-Honney.png" class="bebidas">
                            <span class="desconto">27%<br />OFF</span>
                        </div>
                        <div>
                            <h4>Whisky Jack Daniel's Honey<br />1000ml</h4>
                            <h5><span>179,90</span> | 123,41</h5>
                            <a href="pagina2.html" class="btn btn-dark">+Carrinho</a>
                        </div>
                    </li>

                </ul>
                </div>
            </div>
        </div>
    
    </section>

    <!--====== Menu Dragging Javascrypt ======-->
    <script src="/js/main.js"></script>

    <footer>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container justify-content-center">
                <ul class="navbar-nav">

                    <li class="nav-item">
                        <span class="titulo">Contatos:</span>
                        <span class="nav-link mt-3">(XX) 00000-0000</span>
                        <span class="nav-link">(XX) 00000-0000</span>
                        <span class="nav-link">emporiorinaldi@mail.com</span>
                        <a href="#" class="nav-link">Sobre a Empresa</a>
                    </li>

                    <li class="nav-item">
                        <span class="titulo">Minha Conta:</span>
                        <a href="#" class="nav-link mt-3">Minha conta</a>
                        <a href="#" class="nav-link">Meus pedidos</a>
                        <a href="#" class="nav-link">Rastreamento</a>
                    </li>

                    <li class="nav-item">
                        <span class="titulo">Ajuda:</span>
                        <a href="#" class="nav-link mt-3">Formas de Pagamento</a>
                        <a href="#" class="nav-link">Prazos de entrega</a>
                        <a href="#" class="nav-link">Regras de devolução</a>
                        <a href="#" class="nav-link">Fornecedores</a>
                    </li>

                    <li class="nav-item">
                        <span class="titulo">Redes Sociais:</span>
                        <a href="#" class="nav-link mt-3"><img src="/img/facebook.png" class="icone4">Facebook</a>
                        <a href="#" class="nav-link"><img src="/img/twitter.png" class="icone4">Twitter</a>
                        <a href="#" class="nav-link"><img src="/img/instagram.png" class="icone4">Instagran</a>
                        <a href="#" class="nav-link"><img src="/img/whatsapp.png" class="icone4">WhatsApp</a>
                    </li>

                </ul>
            </div>
        </nav>
    </footer>